### ISSUE TITLE
Hi I'm stuck with 

### ISSUE THREAD

**Issue by DevilsHYPE** [A-Georgiou/SimpleNikeAccountCreator#11]
SimpleNikeAccountCreator>forever botUS.js
'forever' is not recognized as an internal or external command,
operable program or batch file.

hmm. wonder how can i fix this. sorry im very new to programming. but im willing to learn

**Comment by DevilsHYPE** [comment]
submitted
Phone Number: 13047xxxx
Phone number: 3047xxxxxx
waiting 5s
waiting done
Error: No node found for selector: div.sendCode > div.mobileNumber-div > input
    at assert (C:\Users\Vincent-Rig\Documents\GitHub\SimpleNikeAccountCreator\node_modules\puppeteer\lib\helper.js:278:11)
    at Frame.click (C:\Users\Vincent-Rig\Documents\GitHub\SimpleNikeAccountCreator\node_modules\puppeteer\lib\FrameManager.js:736:5)
    at async C:\Users\Vincent-Rig\Documents\GitHub\SimpleNikeAccountCreator\botUS.js:147:7
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Vincent-Rig\Documents\GitHub\SimpleNikeAccountCreator\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.click (C:\Users\Vincent-Rig\Documents\GitHub\SimpleNikeAccountCreator\node_modules\puppeteer\lib\Page.js:973:29)
    at C:\Users\Vincent-Rig\Documents\GitHub\SimpleNikeAccountCreator\botUS.js:147:18
error: Forever detected script exited with code: 0
error: Script restart attempt #2
The Bot is starting...
Terminate batch job (Y/N)? y
