### ISSUE TITLE
Error:  No node found for selector: div.sendCode

### ISSUE THREAD

**Issue by keevang** [A-Georgiou/SimpleNikeAccountCreator#5]
Here is the full error I am getting.

Error: No node found for selector: div.sendCode > div.mobileNumber-div > input
    at assert (C:\Users\Administrator\Desktop\SimpleNikeAccountCreator-master\node_modules\puppeteer\lib\helper.js:231:11)
    at DOMWorld.click (C:\Users\Administrator\Desktop\SimpleNikeAccountCreator-master\node_modules\puppeteer\lib\DOMWorld.js:366:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Administrator\Desktop\SimpleNikeAccountCreator-master\node_modules\puppeteer\lib\helper.js:110:27)
    at Page.click (C:\Users\Administrator\Desktop\SimpleNikeAccountCreator-master\node_modules\puppeteer\lib\Page.js:988:29)
    at C:\Users\Administrator\Desktop\SimpleNikeAccountCreator-master\botUS.js:146:18
error: Forever detected script exited with code: 0
error: Script restart attempt #1

**Comment by mattnook** [comment]
I also have this issue. the console is logging phoneNum as "Phone Number: API support for paid user" which is coming from the 'info' variable. so that's not getting defined properly is my guess

**Comment by CJerome5** [comment]
Getting same exact error. Anyone been able to find a fix it?

**Comment by A-Georgiou** [comment]
They have changed the site and the API, they have moved around and renamed div's so the bot cannot detect and fill them in, this is something to be patched in the next week or so.
The API may also need to be changed as the website host has altered its functionality, also to be changed within the coming weeks.
